/**
 * Submission media (cover + gallery) — image validation & storage.
 *
 * Every uploaded image is treated as untrusted input:
 *   - size is capped (per image);
 *   - the file SIGNATURE decides the type (never the filename or the
 *     client-provided MIME); only JPEG / PNG / WebP are accepted — no GIF,
 *     no HTML, no executables, no anything else;
 *   - dimensions are parsed from the real binary headers and capped;
 *   - storage ids are generated by the server (`media_<ts>_<rand>`); clients
 *     can only ever reference those ids back, never paths.
 *
 * Storage (Cloudflare KV, same namespace as submissions):
 *   m:<mediaId>                -> base64 image, 48h TTL (dies if never used)
 *   ma:<storyId>:<file>        -> permanent copy for ACCEPTED stories
 *                                  (file = assets/cover.jpg | assets/gallery/image-NN.ext)
 */

export const MAX_IMAGE_BYTES = 3 * 1024 * 1024; // 3 MB per image
export const MAX_B64_LENGTH = 4_700_000; // ~3.5 MB decoded headroom (base64 inflates ~4/3)
export const MAX_DIMENSION = 4096; // px, either axis
export const MAX_GALLERY_IMAGES = 8; // per story, cover included
export const MEDIA_TTL_SECONDS = 48 * 60 * 60; // 2x the 24h submission window
export const MAX_MEDIA_LABEL = 80;

export type ImageMime = 'image/jpeg' | 'image/png' | 'image/webp';
export type MediaKind = 'cover' | 'character-portrait' | 'scene' | 'other';

export const MEDIA_ID_RE = /^media_[a-z0-9]{6,16}_[a-z0-9]{6,16}$/;
export const MEDIA_PENDING_REF_RE = /^media\/media_[a-z0-9]{6,16}_[a-z0-9]{6,16}$/;
/** Published, allowlisted asset paths (the ONLY shapes a story package may carry). */
export const MEDIA_PUBLISHED_REF_RE =
  /^assets\/(cover\.(?:jpg|png|webp)|gallery\/image-\d{2}\.(?:jpg|png|webp))$/;

/** Safe ref: either pending `media/<id>` or an exact published shape. */
export function isSafeMediaRef(ref: unknown): boolean {
  if (typeof ref !== 'string') return false;
  if (ref !== ref.trim() || ref.length > 120) return false;
  if (/^https?:\/\//i.test(ref) || ref.startsWith('//') || ref.startsWith('data:')) return false;
  return MEDIA_PUBLISHED_REF_RE.test(ref) || MEDIA_PENDING_REF_RE.test(ref);
}

export function extForMime(mime: ImageMime): string {
  return mime === 'image/png' ? 'png' : mime === 'image/webp' ? 'webp' : 'jpg';
}

export function contentTypeForFile(file: string): string {
  if (file.endsWith('.png')) return 'image/png';
  if (file.endsWith('.webp')) return 'image/webp';
  if (file.endsWith('.jpg') || file.endsWith('.jpeg')) return 'image/jpeg';
  return 'application/octet-stream';
}

export function generateMediaId(now = Date.now()): string {
  const rnd = (Math.random().toString(36) + Math.random().toString(36)).replace(/[^a-z0-9]/g, '').slice(0, 8).padEnd(8, '0');
  return `media_${now.toString(36)}_${rnd}`;
}

/* ---------------- binary parsing ---------------- */

function be16(b: Uint8Array, o: number): number {
  return (b[o] << 8) | b[o + 1];
}
function be32(b: Uint8Array, o: number): number {
  return ((b[o] << 24) | (b[o + 1] << 16) | (b[o + 2] << 8) | b[o + 3]) >>> 0;
}
function le16(b: Uint8Array, o: number): number {
  return (b[o] | (b[o + 1] << 8)) >>> 0;
}
function le24(b: Uint8Array, o: number): number {
  return (b[o] | (b[o + 1] << 8) | (b[o + 2] << 16)) >>> 0;
}

/** Width/height from a PNG header (IHDR is the first chunk, fixed offset). */
function pngDimensions(b: Uint8Array): { width: number; height: number } | null {
  if (b.length < 24) return null;
  return { width: be32(b, 16), height: be32(b, 20) };
}

/** Width/height by scanning JPEG markers for the first SOFn frame header. */
function jpegDimensions(b: Uint8Array): { width: number; height: number } | null {
  let i = 2;
  while (i + 4 < b.length) {
    if (b[i] !== 0xff) {
      i++;
      continue;
    }
    const marker = b[i + 1];
    // Standalone markers without a length segment.
    if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      i += 2;
      continue;
    }
    if (marker === 0xd9) break; // EOI
    if (i + 3 >= b.length) break;
    const segLen = be16(b, i + 2);
    // SOF0..SOF15 except DHT(C4), DAC(C8), DRI(CC) carry the frame size.
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      if (i + 9 > b.length) return null;
      return { height: be16(b, i + 5), width: be16(b, i + 7) };
    }
    i += 2 + segLen;
  }
  return null;
}

/** Width/height from a WebP container (VP8 / VP8L / VP8X). */
function webpDimensions(b: Uint8Array): { width: number; height: number } | null {
  if (b.length < 30) return null;
  const fmt = String.fromCharCode(b[12], b[13], b[14], b[15]);
  if (fmt === 'VP8 ') {
    // Lossy keyframe: 3-byte frame tag, start code 9D 01 2A, then 14-bit LE width/height.
    if (b[19] !== 0x9d || b[20] !== 0x01 || b[21] !== 0x2a) return null;
    return { width: le16(b, 22) & 0x3fff, height: le16(b, 24) & 0x3fff };
  }
  if (fmt === 'VP8L') {
    // Lossless: 1-byte signature 0x2F, then little-endian packed bits:
    // 14-bit width-1, 14-bit height-1, 3-bit alpha, 2-bit version.
    if (b[16] !== 0x2f) return null;
    const v = b[17] | (b[18] << 8); // bit positions 0..15
    const width = 1 + (v & 0x3fff);
    const height = 1 + (((v >> 14) & 0x3) | (b[19] << 2) | ((b[20] & 0xf) << 10));
    return { width, height };
  }
  if (fmt === 'VP8X') {
    // Extended: payload = 1 flag byte + 3 reserved + width-1 (24-bit LE) + height-1.
    return { width: 1 + le24(b, 20), height: 1 + le24(b, 23) };
  }
  return null;
}

export interface ValidatedImage {
  mime: ImageMime;
  ext: string;
  width: number;
  height: number;
  bytes: number;
}

export interface MediaValidationResult {
  ok: boolean;
  issues: { path: string; message: string }[];
  image?: ValidatedImage;
  /** Clean base64 (no data-URI prefix, no whitespace) for storage. */
  base64?: string;
}

/**
 * Decode + validate an uploaded image given as base64 (a data-URI prefix is
 * tolerated and stripped). Returns the validated metadata on success.
 */
export function validateUploadedImage(raw: unknown): MediaValidationResult {
  const issues: { path: string; message: string }[] = [];
  if (typeof raw !== 'string') {
    return { ok: false, issues: [{ path: 'image', message: 'must be a base64 string' }] };
  }
  let s = raw.trim();
  // Tolerate and strip a data-URI prefix; trust NOTHING else from it.
  const dataUri = /^data:[^,]*,/.exec(s);
  if (dataUri) s = s.slice(dataUri[0].length);
  if (!/^[A-Za-z0-9+/]+={0,2}$/.test(s)) {
    return { ok: false, issues: [{ path: 'image', message: 'must be valid base64' }] };
  }
  if (s.length > MAX_B64_LENGTH) {
    issues.push({ path: 'image', message: `too large (max ${Math.floor(MAX_IMAGE_BYTES / 1024 / 1024)} MB)` });
    return { ok: false, issues };
  }

  let bytes: Uint8Array;
  try {
    const bin = atob(s);
    bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  } catch {
    return { ok: false, issues: [{ path: 'image', message: 'malformed base64' }] };
  }
  if (bytes.length === 0) return { ok: false, issues: [{ path: 'image', message: 'empty image' }] };
  if (bytes.length > MAX_IMAGE_BYTES) {
    issues.push({ path: 'image', message: `too large (max ${Math.floor(MAX_IMAGE_BYTES / 1024 / 1024)} MB)` });
    return { ok: false, issues };
  }

  // Signature decides the type.
  let mime: ImageMime | null = null;
  let dims: { width: number; height: number } | null = null;
  if (bytes.length > 2 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    mime = 'image/jpeg';
    dims = jpegDimensions(bytes);
  } else if (
    bytes.length > 8 &&
    bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47 &&
    bytes[4] === 0x0d && bytes[5] === 0x0a && bytes[6] === 0x1a && bytes[7] === 0x0a
  ) {
    mime = 'image/png';
    dims = pngDimensions(bytes);
  } else if (
    bytes.length > 12 &&
    bytes[0] === 0x52 && bytes[1] === 0x49 && bytes[2] === 0x46 && bytes[3] === 0x46 &&
    bytes[8] === 0x57 && bytes[9] === 0x45 && bytes[10] === 0x42 && bytes[11] === 0x50
  ) {
    mime = 'image/webp';
    dims = webpDimensions(bytes);
  } else {
    issues.push({ path: 'image', message: 'only JPEG, PNG and WebP images are accepted' });
    return { ok: false, issues };
  }
  if (!dims) {
    issues.push({ path: 'image', message: 'could not read image dimensions' });
    return { ok: false, issues };
  }
  if (dims.width < 1 || dims.height < 1 || dims.width > MAX_DIMENSION || dims.height > MAX_DIMENSION) {
    issues.push({ path: 'image', message: `dimensions out of range (max ${MAX_DIMENSION}px)` });
    return { ok: false, issues };
  }

  return { ok: true, issues, image: { mime, ext: extForMime(mime), width: dims.width, height: dims.height, bytes: bytes.length }, base64: s };
}

/* ---------------- KV storage ---------------- */

export const MEDIA_KV = {
  /** Pending uploads (48h TTL). */
  PENDING: 'm:',
  /** Permanent copies for accepted stories: ma:<storyId>:<file>. */
  ACCEPTED: 'ma:',
};

export function mediaKey(mediaId: string): string {
  return MEDIA_KV.PENDING + mediaId;
}
export function acceptedMediaKey(storyId: string, file: string): string {
  return MEDIA_KV.ACCEPTED + storyId + ':' + file;
}
export function mediaIdFromRef(ref: string): string | null {
  const m = MEDIA_PENDING_REF_RE.exec(ref);
  return m ? ref.slice('media/'.length) : null;
}
/** Published file name for a pending ref (cover or the Nth gallery slot). */
export function publishedFileForSlot(slot: number, ext: string): string {
  const n = String(slot).padStart(2, '0');
  return `assets/gallery/image-${n}.${ext}`;
}

export function bytesFromBase64(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
