/**
 * Terms & Conditions — displayed in-app (Settings -> About -> Terms)
 * and on the website. Plain language, honest scope.
 * NOTE: This is app text, not legal advice. Get professional legal
 * review before production publication.
 */

export const TERMS_UPDATED = '11 September 2026';

export interface LegalSection {
  heading: string;
  body: string[];
}

export const TERMS_SECTIONS: LegalSection[] = [
  {
    heading: '1. What Kissa is',
    body: [
      'Kissa ("the app") is a local-first interactive AI story/chat application. It lets you play story-driven conversations where you are the main character.',
      'The app works WITHOUT accounts, WITHOUT login, and WITHOUT our own backend servers. Your profile, chats, memories, progress, and settings stay on your device.',
    ],
  },
  {
    heading: '2. No account, no cloud sync',
    body: [
      'There is no account creation, no login, no signup, and no mandatory cloud sync. If you uninstall the app or lose your device without an exported backup, your data cannot be recovered by us — because we never had it.',
      'Use Settings → Storage → Export My Data to move your progress between devices.',
    ],
  },
  {
    heading: '3. AI-generated content',
    body: [
      'Story replies may be generated by third-party AI models (when you configure your own AI provider) or by the built-in Offline Story Mode.',
      'AI-generated content can be wrong, inconsistent, or surprising. It is fiction for entertainment — not advice (medical, legal, financial, or otherwise). Do not rely on it for real-world decisions.',
      'Characters are fictional. Any resemblance to real persons is coincidental.',
    ],
  },
  {
    heading: '4. Your AI provider (BYO-key)',
    body: [
      'Kissa does NOT provide its own AI API, credits, coins, or subscriptions. You may optionally configure your own third-party AI provider with your own API key (Settings → AI Add-ons).',
      'Your API key is stored securely on your device (Android Keystore / iOS Keychain) and is sent ONLY to the provider you configured, as part of your chat requests.',
      'Your provider\'s own terms, pricing, quotas, rate limits, and data policies apply. We are not responsible for your provider\'s billing, availability, or handling of your requests.',
      'The app itself never limits your chatting: no coins, no energy, no message caps from us.',
    ],
  },
  {
    heading: '5. API usage & third-party responsibility',
    body: [
      'When you use a cloud AI provider, the text needed to generate a reply (recent messages, story state, memories) is sent to that provider. Do not share passwords, OTPs, or sensitive personal data in chats.',
      'We do not control third-party providers. If a provider is down, slow, or rejects your key, the app will show an error and you can retry, change settings, or use Offline Story Mode.',
    ],
  },
  {
    heading: '6. Local storage',
    body: [
      'Chats, story progress, memories, favorites, downloads, statistics, and AI configuration metadata are stored in a local on-device database. API keys use secure device storage.',
      'Exported backup files contain your stories and chats — keep them safe. Backup files do NOT contain your API keys; you must re-enter keys after importing.',
    ],
  },
  {
    heading: '7. Story content & age ratings',
    body: [
      'Stories carry age ratings (12–17 or 18+). If you select 12–17, mature stories are hidden and blocked throughout the app, including direct opens.',
      'Downloaded and bundled stories are fiction. Mature (18+) stories may contain dark themes and are intended only for adults.',
      'All sample stories, characters, and artwork in Kissa are original works created for this app.',
    ],
  },
  {
    heading: '8. Acceptable use',
    body: [
      'Use Kissa for personal entertainment. Do not use it to harm others, to generate illegal content, to harass or impersonate real people, or to attempt to extract other users\' data (there are no other users\' data on your device — but still, be kind).',
      'Parents/guardians: the 12–17 catalog is filtered, but AI chat is open-ended. Please supervise younger readers.',
    ],
  },
  {
    heading: '9. Intellectual property',
    body: [
      'The Kissa app, its branding, UI, original stories, characters, artwork, and sounds are the project\'s original works. The open-source repository is available on GitHub under its LICENSE file.',
      'You may export and keep your own chats and playthroughs for personal use.',
    ],
  },
  {
    heading: '10. Updates & content',
    body: [
      'New stories may be distributed through the Kissa story API (manifest + story packages). Downloading content requires internet; stories you already have keep working offline.',
      'We may update these terms. Material changes will be noted with a new "updated" date in-app.',
    ],
  },
  {
    heading: '11. Limitations',
    body: [
      'The app is provided "as is", without warranties of any kind. To the maximum extent permitted by law, we are not liable for lost data, provider charges, or decisions made based on fictional AI content.',
      'AI features depend on providers you choose; availability and quality vary.',
    ],
  },
  {
    heading: '12. Termination & deletion',
    body: [
      'There is no account to terminate. You can stop using the app at any time. Settings → Storage → Delete All Local Data wipes your on-device data; uninstalling also removes it.',
    ],
  },
  {
    heading: '13. Contact',
    body: [
      'Questions? Open an issue on the GitHub repository (Settings → About → GitHub) or email the support address listed in About.',
    ],
  },
];
